// Generated from parser.nodeSet by scripts/generate-syntax-nodes.mjs. Do not edit.
// Numeric term IDs and anonymous/error nodes are deliberately not part of this interface.
export const csoundNodeNames = Object.freeze({
  "ArrayAccessExpr": "ArrayAccessExpr",
  "ArrayBase": "ArrayBase",
  "ArrayIdentifier": "ArrayIdentifier",
  "ArrayIndex": "ArrayIndex",
  "ArrayIndexContent": "ArrayIndexContent",
  "ArrayLiteralContent": "ArrayLiteralContent",
  "ArrayLiteralExpr": "ArrayLiteralExpr",
  "ArrayRangeExpr": "ArrayRangeExpr",
  "ArraySliceExpr": "ArraySliceExpr",
  "ArraySuffix": "ArraySuffix",
  "AssignmentOperator": "AssignmentOperator",
  "AssignmentStatement": "AssignmentStatement",
  "AssignmentTargetAtom": "AssignmentTargetAtom",
  "BlockComment": "BlockComment",
  "BooleanLiteral": "BooleanLiteral",
  "BreakContinueStatement": "BreakContinueStatement",
  "CabbageBlock": "CabbageBlock",
  "CaseBlock": "CaseBlock",
  "ControlStatement": "ControlStatement",
  "CsbeatsScoreBlock": "CsbeatsScoreBlock",
  "CsdCabbageClose": "CsdCabbageClose",
  "CsdCabbageOpen": "CsdCabbageOpen",
  "CsdCloseTag": "CsdCloseTag",
  "CsdDocument": "CsdDocument",
  "CsdElement": "CsdElement",
  "CsdFile": "CsdFile",
  "CsdInstrumentsClose": "CsdInstrumentsClose",
  "CsdInstrumentsOpen": "CsdInstrumentsOpen",
  "CsdItem": "CsdItem",
  "CsdLicenseClose": "CsdLicenseClose",
  "CsdLicenseOpen": "CsdLicenseOpen",
  "CsdOpenTag": "CsdOpenTag",
  "CsdOptionsClose": "CsdOptionsClose",
  "CsdOptionsOpen": "CsdOptionsOpen",
  "CsdPrelude": "CsdPrelude",
  "CsdScoreClose": "CsdScoreClose",
  "CsdScoreOpen": "CsdScoreOpen",
  "CsdScoreOpenCsbeats": "CsdScoreOpenCsbeats",
  "DeclareDefinition": "DeclareDefinition",
  "DefaultBlock": "DefaultBlock",
  "DefineBody": "DefineBody",
  "DefineBodyLine": "DefineBodyLine",
  "DefineBodyStartToken": "DefineBodyStartToken",
  "DefineDirective": "DefineDirective",
  "DefineName": "DefineName",
  "DefineParam": "DefineParam",
  "DefineParamList": "DefineParamList",
  "Ellipsis": "Ellipsis",
  "ElseIfPart": "ElseIfPart",
  "ElsePart": "ElsePart",
  "FlatStatement": "FlatStatement",
  "ForIterator": "ForIterator",
  "ForIteratorName": "ForIteratorName",
  "ForLoop": "ForLoop",
  "FunctionCallExpr": "FunctionCallExpr",
  "FunctionCallStatement": "FunctionCallStatement",
  "FunctionCallee": "FunctionCallee",
  "GenericGroup": "GenericGroup",
  "GenericGroupContent": "GenericGroupContent",
  "GenericLine": "GenericLine",
  "GenericLineToken": "GenericLineToken",
  "GlobalTypedArrayIdentifier": "GlobalTypedArrayIdentifier",
  "GlobalTypedIdentifier": "GlobalTypedIdentifier",
  "GotoStatement": "GotoStatement",
  "HashDefine": "HashDefine",
  "HashElse": "HashElse",
  "HashEnd": "HashEnd",
  "HashIfdef": "HashIfdef",
  "HashIfndef": "HashIfndef",
  "HashInclude": "HashInclude",
  "HashIncludestr": "HashIncludestr",
  "HashLine": "HashLine",
  "HashTerminatedGenericLine": "HashTerminatedGenericLine",
  "HashUndef": "HashUndef",
  "HeaderIdentifier": "HeaderIdentifier",
  "HeaderPrefixedIdentifier": "HeaderPrefixedIdentifier",
  "Identifier": "Identifier",
  "IfStatement": "IfStatement",
  "IncludeDirective": "IncludeDirective",
  "IncludeFile": "IncludeFile",
  "InstrId": "InstrId",
  "InstrIdList": "InstrIdList",
  "InstrumentDefinition": "InstrumentDefinition",
  "InstrumentsBlock": "InstrumentsBlock",
  "LabelName": "LabelName",
  "LabelStatement": "LabelStatement",
  "LabeledStatementTail": "LabeledStatementTail",
  "LegacyTypeIdentifier": "LegacyTypeIdentifier",
  "LegacyUdo": "LegacyUdo",
  "LicenseBlock": "LicenseBlock",
  "LineComment": "LineComment",
  "LineContinuation": "LineContinuation",
  "LooseGenericLine": "LooseGenericLine",
  "LooseKeyword": "LooseKeyword",
  "LooseLineToken": "LooseLineToken",
  "MacroCallArg": "MacroCallArg",
  "MacroCallArgs": "MacroCallArgs",
  "MacroUsage": "MacroUsage",
  "MacroUsageToken": "MacroUsageToken",
  "MemberAccessExpr": "MemberAccessExpr",
  "MemberAccessRoot": "MemberAccessRoot",
  "MemberAccessSegment": "MemberAccessSegment",
  "ModernUdo": "ModernUdo",
  "ModernUdoInputs": "ModernUdoInputs",
  "Number": "Number",
  "OptionsBlock": "OptionsBlock",
  "OrcAddExpr": "OrcAddExpr",
  "OrcAndExpr": "OrcAndExpr",
  "OrcBitAndExpr": "OrcBitAndExpr",
  "OrcBitOrExpr": "OrcBitOrExpr",
  "OrcBitXorExpr": "OrcBitXorExpr",
  "OrcCallExprList": "OrcCallExprList",
  "OrcCompareExpr": "OrcCompareExpr",
  "OrcConditionalExpr": "OrcConditionalExpr",
  "OrcExpr": "OrcExpr",
  "OrcExprGap": "OrcExprGap",
  "OrcExprList": "OrcExprList",
  "OrcGenericLine": "OrcGenericLine",
  "OrcIfdefDirective": "OrcIfdefDirective",
  "OrcMulExpr": "OrcMulExpr",
  "OrcOrExpr": "OrcOrExpr",
  "OrcPowExpr": "OrcPowExpr",
  "OrcPrimary": "OrcPrimary",
  "OrcShiftExpr": "OrcShiftExpr",
  "OrcStatement": "OrcStatement",
  "OrcStatements": "OrcStatements",
  "OrcUnaryExpr": "OrcUnaryExpr",
  "OrchestraFile": "OrchestraFile",
  "PField": "PField",
  "ParenthesizedExpr": "ParenthesizedExpr",
  "PlusInstrId": "PlusInstrId",
  "PreprocessorDirective": "PreprocessorDirective",
  "PreprocessorName": "PreprocessorName",
  "RawString": "RawString",
  "ReturnStatement": "ReturnStatement",
  "ScoStatement": "ScoStatement",
  "ScoStatements": "ScoStatements",
  "ScoreAddExpr": "ScoreAddExpr",
  "ScoreAndExpr": "ScoreAndExpr",
  "ScoreBitAndExpr": "ScoreBitAndExpr",
  "ScoreBitOrExpr": "ScoreBitOrExpr",
  "ScoreBlock": "ScoreBlock",
  "ScoreBracketExpr": "ScoreBracketExpr",
  "ScoreCarry": "ScoreCarry",
  "ScoreCompareExpr": "ScoreCompareExpr",
  "ScoreContinuationLine": "ScoreContinuationLine",
  "ScoreExpr": "ScoreExpr",
  "ScoreExprAtom": "ScoreExprAtom",
  "ScoreExprList": "ScoreExprList",
  "ScoreField": "ScoreField",
  "ScoreFieldAtom": "ScoreFieldAtom",
  "ScoreFile": "ScoreFile",
  "ScoreFunctionCallExpr": "ScoreFunctionCallExpr",
  "ScoreFunctionCallee": "ScoreFunctionCallee",
  "ScoreIfdefDirective": "ScoreIfdefDirective",
  "ScoreLoopBody": "ScoreLoopBody",
  "ScoreMulExpr": "ScoreMulExpr",
  "ScoreNestableLoop": "ScoreNestableLoop",
  "ScoreNestedPrimary": "ScoreNestedPrimary",
  "ScoreOpcode": "ScoreOpcode",
  "ScoreOrExpr": "ScoreOrExpr",
  "ScorePowExpr": "ScorePowExpr",
  "ScorePreprocessor": "ScorePreprocessor",
  "ScoreRelativePField": "ScoreRelativePField",
  "ScoreRelativePFieldName": "ScoreRelativePFieldName",
  "ScoreRelativeTime": "ScoreRelativeTime",
  "ScoreSharpNote": "ScoreSharpNote",
  "ScoreShiftExpr": "ScoreShiftExpr",
  "ScoreSimpleExpr": "ScoreSimpleExpr",
  "ScoreStatementLine": "ScoreStatementLine",
  "ScoreTilde": "ScoreTilde",
  "ScoreUnaryExpr": "ScoreUnaryExpr",
  "String": "String",
  "StructDefinition": "StructDefinition",
  "StructField": "StructField",
  "SwitchBody": "SwitchBody",
  "SwitchStatement": "SwitchStatement",
  "ThenPart": "ThenPart",
  "TrailingContent": "TrailingContent",
  "TypedArrayIdentifier": "TypedArrayIdentifier",
  "TypedIdentifier": "TypedIdentifier",
  "UdoArgType": "UdoArgType",
  "UdoArgTypes": "UdoArgTypes",
  "UdoBody": "UdoBody",
  "UdoDefinition": "UdoDefinition",
  "UdoName": "UdoName",
  "UdoParam": "UdoParam",
  "UdoParamList": "UdoParamList",
  "UdoReturnSpec": "UdoReturnSpec",
  "UdoReturnType": "UdoReturnType",
  "UdoReturnTypeList": "UdoReturnTypeList",
  "UdoSignatureGap": "UdoSignatureGap",
  "UdoTypeName": "UdoTypeName",
  "UndefDirective": "UndefDirective",
  "UntilLoop": "UntilLoop",
  "UntilLoopTerminator": "UntilLoopTerminator",
  "WhileLoop": "WhileLoop",
  "XoutStatement": "XoutStatement",
  "break": "break",
  "case": "case",
  "continue": "continue",
  "declare": "declare",
  "default": "default",
  "do": "do",
  "else": "else",
  "elseif": "elseif",
  "endif": "endif",
  "endin": "endin",
  "endop": "endop",
  "endsw": "endsw",
  "enduntil": "enduntil",
  "false": "false",
  "falsek": "falsek",
  "fi": "fi",
  "for": "for",
  "goto": "goto",
  "if": "if",
  "igoto": "igoto",
  "in": "in",
  "instr": "instr",
  "ithen": "ithen",
  "kgoto": "kgoto",
  "kthen": "kthen",
  "np": "np",
  "od": "od",
  "opcode": "opcode",
  "pp": "pp",
  "reinit": "reinit",
  "return": "return",
  "rigoto": "rigoto",
  "rireturn": "rireturn",
  "struct": "struct",
  "switch": "switch",
  "then": "then",
  "true": "true",
  "truek": "truek",
  "until": "until",
  "void": "void",
  "while": "while",
  "xin": "xin",
  "xout": "xout",
} as const)

export type CsoundNodeName = keyof typeof csoundNodeNames

export const csoundNodeGroups = Object.freeze({
  "CsoundIdentifier": Object.freeze([
    "ArrayIdentifier",
    "GlobalTypedArrayIdentifier",
    "GlobalTypedIdentifier",
    "HeaderIdentifier",
    "Identifier",
    "LegacyTypeIdentifier",
    "PField",
    "TypedArrayIdentifier",
    "TypedIdentifier",
  ] as const),
  "CsoundTypedIdentifier": Object.freeze([
    "GlobalTypedArrayIdentifier",
    "GlobalTypedIdentifier",
    "TypedArrayIdentifier",
    "TypedIdentifier",
  ] as const),
} as const)

export const csoundTopNodeNames = Object.freeze(["CsdFile","OrchestraFile","ScoreFile"] as const)
export type CsoundTopNodeName = typeof csoundTopNodeNames[number]
